try:
    result = 45/0
except:
    print("Error happened")
finally:
    print("Finally here")